name = "main"
workers_dev = true

# 运行时的入口脚本
main        = "disk/_worker.js"

# 把 disk/ 当成站点资源目录，但排除掉 _worker.js
site = { 
  bucket  = "./disk", 
  include = ["**/*"], 
  exclude = ["_worker.js"]    # ← 这行会让 Wrangler 上传时跳过它
}
compatibility_date = "2025-06-08"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "LIKES"
id      = "d0ecfe6f05a243ee9833040dbf4f0fc7"
